### ISSUE TITLE
Welcome!

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs-es#1]
Welcome, new localizations team :)

To get this team up and running you have a few initial tasks to accomplish:

- [x] Create a README.md for this repository, it should include:
  - [x] A "call to action" pointing to the Issue tracker for new translators to find tasks.
  - [x] A list of the team members.
  - [x] Instructions on how to log an issue to be added to this team.
- [x] Set the repository description. This should not be in English, it should be in the language for this community :)
 - [x] Social Media
 - [x] Create a twitter account for this language. Share the password privately with the team.
 - [x] Create accounts on other social media popular in this language. Share the passwords private with the rest of the team.
 - [ ] Make sure you use these accounts not just to promote newly translated material but also to attract people in your community to help with translation tasks.
 - [ ] *Optional:* If you plan to do a Google hangout w/ your localization team have @mikeal add you to the Google+ account so that it can post to the `iojs` YouTube channel. Once you are added there is [documentation on how to setup a hangout-on-air](https://github.com/iojs/io.js/wiki/Meetings:-Creating-a-Hangouts-On-Air-Event).
- [x] Finally, create a new Issue to translate and publish the [latest io.js post](https://medium.com/@iojs). Once translated you should post it wherever you think it will get the most visibility to the community speaking you language, you don't have to post it to Medium unless you think that it is best.

**Comment by edsadr** [comment]
Ok so far the README is done and the description was changed, some items at the README are missing because  would be nice to have an open discussion about the best approach to work, establish the rules submitting issues and assigning them.

I tried to register at Twitter but @ios_es is taken, not sure if someone owns it here?

**Comment by stringparser** [comment]
Is @iojs_es taken? let me check. Yes it is, sure has to be someone here, is empty. I still can commit anything I guess mikeal is waiting to have more people. Anyhow, I can take the translate post part.

**Comment by stringparser** [comment]
I wanted to write "I still cannot commit" haha, these fingers... :)

**Comment by mikeal** [comment]
I think maybe @a0viedo or @julianduque registered twitter, they'll pop in here soon :)

**Comment by stringparser** [comment]
Ok, in the mean time I have written to this account. Let see :D

**Comment by stringparser** [comment]
For sharing passwords this is what

**Comment by a0viedo** [comment]
Hey everyone, I don't registered @iojs_es. Maybe @julianduque?

> Finally, create a new Issue to translate and publish the latest io.js post. Once translated you should post it wherever you think it will get the most visibility to the community speaking you language, you don't have to post it to Medium unless you think that it is best.

Can we discuss this? I created the translation on Medium, but I don't know if it's the best way to get visibility.

**Comment by stringparser** [comment]
I don't know either, but I think Medium is the place. Alternatives would be wordpress or blogspot, in es_ES at least. Anyhow, what do you guys think?

**Comment by alejonext** [comment]
I think there are better options, I suggest using [Ghost](https://github.com/TryGhost/Ghost), but not if now multilanguage

**Comment by julianduque** [comment]
I registered @iojs_es but was disconnected from the interwebs for a week, password was shared with the team so all good now, sorry for not sharing it on time :sweat_smile:

**Comment by stringparser** [comment]
I'm just glad you are here :smile:
