### ISSUE TITLE
Follow up de #80 (propuesta de reonciliación)

### ISSUE THREAD

**Issue by stringparser** [nodejs/nodejs-es#123]
Han cerrado el issue original donde se hizo la prouesta [iojs/io.js#978](https://github.com/iojs/io.js/issues/978#issuecomment-101410027). En el issue de abajo están recopilando toda la información al respecto: 

[iojs/io.js#1664 - Join the Node Foundation?](https://github.com/iojs/io.js/issues/1664)

**Comment by edsadr** [comment]
yup y segun veo nos clasificaron como WG Mature y vamos en el merging a ser el equipo oficial de Node en español :) ... hay que organizarnos definitivamente :P

**Comment by stringparser** [comment]
Si tío, hay que echarle un buen rato a esto pa ponerlo al día. Lo primero es traducir lo que hay del website y los artículos de evangelización que hay pendientes. Se podría empezar por los más recientes.

**Comment by pandres95** [comment]
Eso estaba pensando esta tarde, empezaré entonces por los artículos más recientes.

**Comment by stringparser** [comment]
:+1:

**Comment by srl295** [comment]
Debemos que cambar el nombre del repo *`iojs-`*? Ya creó un issue [porque el TSC pueden den información sobre el cambiar](nodejs/node#2525).

**Comment by edsadr** [comment]
Para esto necesitamos alguien que tenga permisos sobre el repo @stringparser tienes?

**Comment by stringparser** [comment]
Pues no tengo, creo que todos somos colaboradores @edsadr

**Comment by srl295** [comment]
> no somos los únicos

Sí, precisamente.. Yo pienso es un poco mejor que esperamos después de la próxima junto del TSC (mañana, miércoles)  y den respuesta a https://github.com/nodejs/iojs-es/issues/nodejs/node#2525.

**Comment by stringparser** [comment]
Este podemos cerrarlo también entonces
