### ISSUE TITLE
publicaciones y traductor

### ISSUE THREAD

**Issue by stringparser** [nodejs/nodejs-es#130]
¡Buenas!

He publicado los artículos que @pandres95 dejo en [iojs-es/evangelism](https://github.com/iojs-es/evangelism) pero aún no estaban en [medium](https://medium.com/@iojs_es) y al hacerlo he estado pensando que estaría bien atribuir la traducción a la persona que la hizo y los correctores al final de los artículos. 

Está reflejado en la PR, pero no está de más ponerlo también en el artículo como nota al final para motivar a la gente que traduzca. 

Una idea, ya me contáis qué os parece
cc @nodejs/iojs-es

**Comment by sergiolepore** [comment]
:+1:

**Comment by edsadr** [comment]
:+1: creo que el credito es importante

**Comment by pandres95** [comment]
Gracias @stringparser por publicarlos, a mi ya se me estaba olvidando ese detalle. Ya empecé la siguiente tanda de traducciones :smile:

**Comment by stringparser** [comment]
@pandres95 de lujo. A ver si hay alguien de iojs-es/evangelism que te pueda echar una mano con las traducciones (@julianduque, @vrunoa, @academo, @a0viedo, @eafelix, @devjluna)

**Comment by vrunoa** [comment]
Entre esta noche y mañana a la mañana lo miro. Disculpen que estuve medio ausente.

**Comment by ipeluffo** [comment]
Si agregar los colaboradores de la traducción es una manera de incentivar a más gente, estoy de acuerdo :)

Por otro lado, no dejaría de mencionar al WG

**Comment by vrunoa** [comment]
Chicos, deje algunas anotaciones en el PR [https://github.com/iojs-es/evangelism/pull/7](https://github.com/iojs-es/evangelism/pull/7), a ver que les parece.

**Comment by stringparser** [comment]
@vrunoa te ayudo a mejorar la traducción ahora

**Comment by stringparser** [comment]
@vrunoa he abierto una PR para que hagas los cambios que necesites (iojs-es/evangelizacion#11)

Aunque estaría bien traducir lo que falta primero :stuck_out_tongue_closed_eyes:

**Comment by vrunoa** [comment]
@stringparser cuales son los documentes que faltarían traducir ? disculpen estuve medio ausente y estoy medio perdido. 
El chat de gitter esta operativo ?

**Comment by stringparser** [comment]
@vrunoa yo miro [gitter](https://gitter.im/nodejs/iojs-es) y [slack](https://nodejs-es.slack.com/messages/general/) de vez en cuando. Pues de [iojs-es/evangelism](https://github.com/iojs-es/evangelism) los que veas que aún estén aquí [iojs-es/evangelism/weekly-updates](https://github.com/iojs-es/evangelism/tree/master/weekly-updates)

**Comment by vrunoa** [comment]
Perfect. En un rato los miro, y traduzco alguno. 

En slack no estoy agregado.

**Comment by stringparser** [comment]
Habla con @pandres95 para que te agrege a slack

**Comment by rcotrina94** [comment]
¿También coordinan por slack? Yo sólo seguía el gitter D:

**Comment by sergiolepore** [comment]
@rcotrina94 Gitter, Slack, HipChat, WhatsApp (?)

**Comment by SametSisartenep** [comment]
WhatsApp no please :cry:.

**Comment by sergiolepore** [comment]
@SametSisartenep fue en broma 😁

**Comment by SametSisartenep** [comment]
:stuck_out_tongue_closed_eyes:

**Comment by rcotrina94** [comment]
@sergiolepore @SametSisartenep Telegram FTW :+1:
