### ISSUE TITLE
Traducir Slides Roadmap

### ISSUE THREAD

**Issue by julianduque** [nodejs/nodejs-es#66]
Todavía es un work in progress pero dejo esto por acá para que lo tengamos pendiente

http://roadmap.iojs.org/

https://github.com/iojs/roadmap

**Comment by vrunoa** [comment]
Donde deberíamos crear el archivo para traducir este documento ? Se debería hacer un fork desde iojs-es a [https://github.com/iojs/roadmap](https://github.com/iojs/roadmap) ? O se crea un roadmap.md en [https://github.com/iojs/iojs-es](https://github.com/iojs/iojs-es) ?

**Comment by ipeluffo** [comment]
Se da la misma situación con el repo https://github.com/iojs/website .
Hasta ahora creo que copian a mano lo que estaba en el repo original, es decir, la segunda opción.

Sin embargo, @stringparser propuso una posible solución en el siguiente comentario https://github.com/iojs/iojs-es/issues/38#issuecomment-74962069 .

Quedo a la espera de comentarios de otros colaboradores porque no se cual es la mejor alternativa para tratar los contenidos de los repositorios [roadmap](https://github.com/iojs/roadmap) y [website](https://github.com/iojs/website)

**Comment by julianduque** [comment]
Yo esperaría a que el Deck esté terminado y copiamos el repo [roadmap](http://github.com/iojs/roadmap) como propone @stringparser y ahí si trabajar en el ya que si lo hacemos ahora podríamos tener dificultades de sync

**Comment by vrunoa** [comment]
No había visto ese [comnent](https://github.com/iojs/iojs-es/issues/38#issuecomment-74962069), apoyo la propuesta de @stringparser

**Comment by julianduque** [comment]
Según leo ya está listo el roadmap, así que podemos empezar a traducir!

**Comment by ipeluffo** [comment]
:+1:

**Comment by stringparser** [comment]
Hey, perdonad que he estado un poco perdido. Encantado de que os guste la idea :). 

¿Hacemos una branch para cada repo? La verdad es que no he intentado "simular un PR" con este método, lo hago en un rato y os cuento.

**Comment by stringparser** [comment]
Roadmap listo para traducir iojs/roadmap#18

**Comment by julianduque** [comment]
Pull request en https://github.com/iojs-es/roadmap/pull/1 Por favor revisar cc @iojs-es/revision
