### ISSUE TITLE
Traducción API - Sección "HTTPS"

### ISSUE THREAD

**Issue by italoacasas** [nodejs/nodejs-es#79]
Please vallan actualizando https://github.com/iojs/iojs-es/issues/73 para poder ir viendo que falta, etc...

Soy el traductor mas seguro de todos lol.

**Comment by stringparser** [comment]
hahaha, perfect. Yo hasta el domingo por ejemplo no voy a poder, pero lo haré :)

**Comment by ipeluffo** [comment]
@italoacasas , ¿estás trabajando en esta sección?

**Comment by italoacasas** [comment]
Voy a comenzar, pero todo el que quiera es bienvenido @ipeluffo

**Comment by ipeluffo** [comment]
@italoacasas , ahí te agregué como colaborador del repo y te asigné el issue :+1:

**Comment by italoacasas** [comment]
Gracias

**Comment by stringparser** [comment]
@italoacasas te he dejado este issue en el comentario de @eafelix ;)
