### ISSUE TITLE
Grupos de Trabajo - WG iojs-es

### ISSUE THREAD

**Issue by julianduque** [nodejs/nodejs-es#83]
Necesitamos definir grupos de trabajo para iojs-es y enfocarnos en los siguientes frentes

# Website

* [iojs/website](http://github.com/iojs/website)

Traducción, sincronización y actualización del sitio web con la página original en inglés.

#### Miembros
* @edsadr
* @stringparser
* @vrunoa 
* @gollodev 

# Documentación

* [iojs/io.js](http://github.com/iojs/io.js)

Traducción, sincronización y actualización de la documentación (API) de io.js con la versión original en inglés.

#### Miembros
* @SametSisartenep 
* @007lva 
* @stringparser
* @a0viedo 
* @eafelix 
* @byoigres

# Evangelización

* [iojs/evangelism](http://github.com/iojs/evangelism)
* [iojs/roadmap](http://github.com/iojs/roadmap)

Traducción, sincronización y actualización de las publicaciones semanales, publicar a medium, publicar a twitter y roadmap

#### Miembros

* @julianduque
* @vrunoa 
* @academo 
* @a0viedo 
* @eafelix 
* @devjluna

# Revisión

Equipo encargado de revisar y dar los +1 necesarios a los contenidos antes de publicarlos

#### Miembros
* @italoacasas
* @edsadr

**Comment by SametSisartenep** [comment]
Contad conmigo en el tema de la **Documentación** ;)

**Comment by julianduque** [comment]
Yo me uno al de Evangelización ya que hago parte del WG oficial

**Comment by edsadr** [comment]
congrats @julianduque me suena website y documentación ...

**Comment by italoacasas** [comment]
Yo hasta que este terminada toda la traducción de la Documentación me uno a ese equipo, ya que me interesa mucho para poder ensenarle a niños que no hablen ingles. Luego ya vere...

**Comment by 007lva** [comment]
+1 para la Documentación

**Comment by italoacasas** [comment]
Ya te agregue @007lva

**Comment by stringparser** [comment]
tomaya! esto ya empieza a tomar forma, yo +1 para todo :dancer:

**Comment by vrunoa** [comment]
Buenas, me sumo para ayudar, si puede ser website o evangelización.

**Comment by stringparser** [comment]
listo ;)

**Comment by a0viedo** [comment]
me sumo a Documentación y Evangelización

voy a encargarme de dar charlas sobre qué es io.js en las meetups locales...hasta podríamos dar la charla en JSConfUY con @julianduque

**Comment by academo** [comment]
Me sumo a evangelización

**Comment by eafelix** [comment]
Me sumo en documentación y evangelización, ya dimos iniciativa con @SametSisartenep y @a0viedo  :p

**Comment by julianduque** [comment]
@ipeluffo me gustaría mucho que fueras parte del equipo de revisión, tus skills gramaticales me han sido de mucha utilidad en el pasado :) es algo que te interesa?

**Comment by julianduque** [comment]
Otro aspecto para tener en cuenta, debido a que el trabajo es mucho la idea es que una persona no esté en más de 2 grupos a la vez pues tendrá mucha carga

**Comment by ipeluffo** [comment]
@julianduque , iba a escribir en este post y se me paso.
Dale, me sumo al equipo de revisión. Si tengo más tiempo me sumo a algún otro. :+1:

**Comment by stringparser** [comment]
+1 @julianduque me parece de lujo, me he quedado en documentación y website

**Comment by edsadr** [comment]
:dancers: voy a trabajar con @stringparser en los 2 grupos .. wohoo :P

**Comment by stringparser** [comment]
@edsadr ahahaha yay!! Yo quería revisar pero también estar en website y documentación. Supongo que la gente que está en documentación de una forma u otra tiene que revisar también

**Comment by sergiolepore** [comment]
:) hay lugar en website y revisión?

**Comment by stringparser** [comment]
Cerramos este también ya que la división de trabajo está en marcha

**Comment by GolloDev** [comment]
voy a Website!

**Comment by byoigres** [comment]
Me uno a GT - Documentación

**Comment by devjluna** [comment]
Me sumo a la evangelización

**Comment by stringparser** [comment]
Ok :)

**Comment by stringparser** [comment]
Dejo este abierto como issue de referencia mientras hacemos un CONTRIBUTING.md en el repositorio

**Comment by ulisesqg** [comment]
Me uno a Evangelización y Website o/

**Comment by ripper2hl** [comment]
Bien me quiero unir a website (de preferencia) o a revisión y queria saber si es posible implementar [slack](https://slack.com/) , escuche que funciona muy bien para la organización de los equipos.

**Comment by stringparser** [comment]
Ok, puedes unirte a los dos ;)
Ahora mismo [tenemos gitter](https://gitter.im/iojs/iojs-es). Si quieres pasate y saluda por allí. 
No he probado slack, pero he escuchado hablar en algún que otro issue del iojs/website.

Acabo de ver el vídeo de slack y a parte de hacerme reír me ha dejado curioso. Voy a ver si es gratizzz :D

**Comment by SametSisartenep** [comment]
@stringparser Sí es gratuito, pero creo que tiene un límite de mensajes y equipos o canales :).
Yo lo estoy usando en un proyecto, con tres personas más, y está muy bien, pero yo creo que la combinación de "Gitter", "Transifex" y "Github" funciona genial :D

**Comment by ripper2hl** [comment]
okay , si es lo malo tiene un limite, prefiero solo unirme a website

**Comment by stringparser** [comment]
ok

**Comment by pandres95** [comment]
Cuenten conmigo en *Evangelización* :)

**Comment by davidjgomez** [comment]
Hola! creo que ya no hay mucha actividad por aquí, pero quisiera preguntar si puedo colaborar en algo, teniendo en cuenta que soy nuevo en io.js (aprendiendo con el buen profe @julianduque) y hasta en GitHub soy relativamente nuevo :P, gracias!

**Comment by kiokotzu** [comment]
+1 para la Documentación
