### ISSUE TITLE
GT - Documentación

### ISSUE THREAD

**Issue by stringparser** [nodejs/nodejs-es#94]
Muy buenas, 

aquí dejo la lista de la gente que está implicada en el Grupo de Trabajo (GT) de Documentación como veníamos hablando en #84. Utilicemos este issue para ir viendo cómo nos vamos a organizar en el repositorio correspondiente de la org. [iojs-es](http://github.com/iojs-es) que @edsadr creó donde vamos a ir dividiendo y asignando tareas.

Estamos 5 por ahora, dejo un ping para todo el que quiera apuntarse: @iojs/iojs-es. 
@eafelix  te asigno para estar al tanto de lo que aquí pase por poner esa lista tan buena para la documentación de la api en #73. 

Recordad que @julianduque dejó la propuesta de **estar como máximo en 2 grupos** con la idea de no sobrecargar a la gente con trabajo. En #83 hay una lista de todos los grupos de trabajo y sus miembros.

Una vez estemos organizados parasaremos a discutir en [iojs-es/io.js](https://github.com/iojs-es/io.js)

# Documentación

* [iojs-es/io.js](http://github.com/iojs-es/io.js)

Traducción, sincronización y actualización de la documentación (API) de io.js con la versión original en inglés.

#### Miembros
* @SametSisartenep 
* @007lva 
* @stringparser
* @a0viedo 
* @eafelix 
* @byoigres

#### Issues pendientes :ghost: :smile: 
* #93 - Traducción API - Sección 'C/C++ Addons'
* #92 - Traducción API - Sección "Readline"
* #89 - Traducción API - Sección "Buffer"
* #87 - Traducción API - Sección "Assert"

**Comment by eafelix** [comment]
Items de la documentación. 

- [ ] About these Docs
- [ ] Synopsis
- [ ] Assertion Testing (@stringparser - #87)
- [ ] Buffer (@stringparser - #89)
- [ ] C/C++ Addons ( @SametSisartenep - #78 )
- [ ] Child Processes
- [ ] Cluster
- [ ] Console
- [ ] Crypto ( @a0viedo )
- [ ] Debugger
- [ ] DNS
- [ ] Domain
- [ ] Errors
- [ ] Events
- [ ] File System
- [ ] Globals
- [ ] HTTP
- [ ] HTTPS ( @italoacasas - #79 )
- [x] Modules
- [ ] Net
- [ ] OS
- [ ] Path
- [ ] Process
- [ ] Punycode
- [ ] Query Strings
- [ ] Readline (@stringparser - #92)
- [ ] REPL
- [ ] Smalloc
- [ ] Stream ( @eafelix )
- [ ] String Decoder
- [ ] Timers
- [ ] TLS/SSL
- [ ] TTY
- [ ] UDP/Datagram
- [ ] URL
- [ ] Utilities
- [ ] V8
- [ ] VM
- [ ] ZLIB

**Comment by SametSisartenep** [comment]
Me acabo de asignar dos nuevas secciones. Voy a comenzar por **ZLIB**, si a alguien le interesa alguna, avisadme, sin problema ;)

**Comment by stringparser** [comment]
¡Grande! :) Yo voy a ver si corrijo lo que dejé hecho. 

Os parece que vayamos migrando el material de aquí a ¿[iojs-es/io.js](http://github.com/iojs-es/io.js)?

**Comment by SametSisartenep** [comment]
@stringparser Genial, cuando queráis. :metal:

**Comment by stringparser** [comment]
@SametSisartenep al final ayer me puse una peli y poco más. Necesito descasar un poco xD. Pero de este fin de semana no pasa que todo lo que @ipeluffo me indicó este corregido, una PR con los términos que haya que añadir de las 3 traducciones y moverlo a la org de iojs-es. Ahora, que esto termine siendo el domingo por la noche es muy probable xD

**Comment by SametSisartenep** [comment]
@stringparser No te preocupes, hay mucho trabajo y relajarse de vez en cuando siempre es positivo :stuck_out_tongue_winking_eye: 
De momento estoy con **zlib** y a la espera del grupo de corrección para saber si debo cambiar algo en la traducción de **Addons**.

Avisadme cuando comencéis a hacer los cambios, así os ayudo en lo que pueda ;)

**Comment by stringparser** [comment]
@SametSisartenep perfect :) y gracias tío. Si, ya te digo, supongo que el domingo :dancers:

**Comment by eafelix** [comment]
Chicos, cualquier nuevo traductor tratemos de involucrarlos con la documentación así la tenemos lo antes posible (algo importante para tener recursos para la evangelización).
Gracias a todos por el esfuerzo!

**Comment by byoigres** [comment]
Quiero ayudar a traducir la API. D:
¡Demén un tema!

**Comment by eafelix** [comment]
Selecciona uno de los modulos de la documentacion que mas te interese y este disponible (ver la lista al inicio del issue) y notificalo

**Comment by SametSisartenep** [comment]
@byoigres Apunta tu nombre al lado de la sección que escojas para llevar un registro limpio ;), y bienvenido al WG de Documentación! :metal:

**Comment by stringparser** [comment]
Equipo de documentación hecho en https://github.com/orgs/iojs-es/teams

**Comment by byoigres** [comment]
Ok, tomaré Child Processes y Console :)

**Comment by byoigres** [comment]
Una pregunta, ¿el fork debe ser de iojs/io.js o iojs-es/io.js?

**Comment by stringparser** [comment]
Ahora mismo da igual, pero si debería ser de iojs-es/io.js. Una cosa, vo ya hacer una branch solo para hacer las PRs de documentación.

**Comment by stringparser** [comment]
Y le voy a poner de nombre... api por ejemplo :smile:

**Comment by stringparser** [comment]
Listo https://github.com/iojs-es/io.js/tree/api, hagamos las PRs de documentación a esa branch ok?

**Comment by SametSisartenep** [comment]
@stringparser :metal:

**Comment by 007lva** [comment]
Me acabo de asignar la sección de Cluster

**Comment by rigoxls** [comment]
Saludos, me gustaría colaborar en este issue !!, Pero me gustaría mas info sobre como estan organizados, a donde hacer el fork y los pull request.. Gracias

**Comment by stringparser** [comment]
Buenas @rigoxls!, 

Estamos trabajando desde esta la org [iojs-es](http://github.com/iojs-es) donde tenemos un fork de cada repositorio que hay que localizar (en el caso de la documentación [iojs-es/io.js](http://github.com/iojs-es/io.js), mira las pull request que hay cerradas para más info). Y si no pregunta por aquí ;)

**Comment by stringparser** [comment]
Y las PRs cerradas me refiero a las que se han dejado puestas en el comentario de @eafelix ;).

**Comment by cesarloachamin** [comment]
Hola acabo de unirme al proyecto me gustaría apoyar en la traducción de los siguientes módulos [Os, Path], si es que alguien mas no esta trabajando en ellos ;)

**Comment by stringparser** [comment]
Parece que no, te pongo en la lista de @eafelix

**Comment by cesarloachamin** [comment]
Ok Muchas gracias ya empiezo a trabajar en estos 2 módulos :)

**Comment by stringparser** [comment]
@cesarloachamin, guay. Si tienes tiempo libre puedes traducir lo que hay pendiente en el [website](https://github.com/iojs-es/website/pull/7) que vendría mejor.

**Comment by cesarloachamin** [comment]
Claro @stringparser, no hay problema igual dejo tomado los 2 módulos continuarlos después de terminar lo del website.
