### ISSUE TITLE
GT - Evangelización

### ISSUE THREAD

**Issue by stringparser** [nodejs/nodejs-es#95]
Muy buenas, 

aquí dejo la lista de la gente que está implicada en el Grupo de Trabajo (GT) de Evangelización por ahora como veníamos hablando en #84. Utilicemos este issue para ir viendo cómo nos vamos a organizar en el repositorio correspondiente de la org. [iojs-es](http://github.com/iojs-es) que @edsadr creó donde vamos a ir dividiendo tareas.

Estamos 3 por ahora, dejo un ping para todo el que quiera apuntarse: @iojs/iojs-es. 
@julianduque te asigno para estar al tanto de lo que aquí pase, porque *you are our guru* :). 

Recordad que @julianduque dejó la propuesta de **estar como máximo en 2 grupos** con la idea de no sobrecargar a la gente con trabajo. En #83 hay una lista de todos los grupos de trabajo y sus miembros.

Una vez estemos organizados parasaremos a discutir en [iojs-es/website](https://github.com/website)

# Evangelización

* [iojs/evangelism](http://github.com/iojs/evangelism)
* [iojs/roadmap](http://github.com/iojs/roadmap)

Traducción, sincronización y actualización de las publicaciones semanales, publicar a medium, publicar a twitter y roadmap

#### Miembros

* @julianduque
* @vrunoa 
* @academo 
* @a0viedo 
* @eafelix 
* @devjluna

#### Issues pendientes
* Publicación Febrero 27 #81 
* Publicación Marzo 6 #101

**Comment by julianduque** [comment]
Excelente @stringparser muchas gracias por crear este issue!

@vrunoa @academo @a0viedo @eafelix definamos una reunión, si es posible a inicios de la próxima semana para que definamos como vamos a trabajar y como nos vamos a repartir las tareas :)

**Comment by eafelix** [comment]
Genial @julianduque , ya @a0viedo esta propienido charlas aca en Arg (tal vez Chile tambien) para comenzar la evangelización, me gusta la idea de la definición de trabajo y repartir tareas para alinearnos.

**Comment by fcanela** [comment]
Estaría encantado de echar un cable, ¿de qué maneras me puedo involucrar?

**Comment by vrunoa** [comment]
dale @julianduque pongamos fecha para hablar. disculpen que no pude estar en el hangout del otro dia, me adecuo a las formas de trabajo que hayan decidido.

**Comment by julianduque** [comment]
El doodle: http://doodle.com/by648bmeb9dkthnf

**Comment by vrunoa** [comment]
:+1:

**Comment by stringparser** [comment]
Equipo de evangelización hecho en https://github.com/orgs/iojs-es/teams

**Comment by julianduque** [comment]
:+1:

**Comment by paulomcnally** [comment]
Me puedo apuntar en este equipo? Saludos

**Comment by a0viedo** [comment]
buenas, se hizo esta reunión?

**Comment by julianduque** [comment]
@a0viedo no se hizo todavìa, he estado este par de semanas un poco fuera de base pero si la debemos hacer
