### ISSUE TITLE
GT - Website

### ISSUE THREAD

**Issue by stringparser** [nodejs/nodejs-es#96]
Muy buenas, 

aquí dejo la lista de la gente que está implicada en el Grupo de Trabajo (GT) del Website por ahora como veníamos hablando en #84. Utilicemos este issue para ir viendo cómo nos vamos a organizar en el repositorio correspondiente de la org. [iojs-es](http://github.com/iojs-es) que @edsadr creó donde vamos a ir dividiendo tareas.

Estamos 3 por ahora, dejo un ping para todo el que quiera apuntarse: @iojs/iojs-es. 
Me asigno para estar al tanto de lo que aquí pase, si alguien quiere tomar cargo que me lo diga y lo asigno ¿ok? :), sin problema. 

Recordad que @julianduque dejó la propuesta de **estar como máximo en 2 grupos** con la idea de no sobrecargar a la gente con trabajo. En #83 hay una lista de todos los grupos de trabajo y sus miembros.

Una vez estemos organizados parasaremos a discutir en [iojs-es/website](https://github.com/website)

# Website
* [iojs/website](http://github.com/iojs/website)

Traducción, sincronización y actualización del sitio web con la página original en inglés.

#### Miembros
* @edsadr
* @stringparser
* @vrunoa 
* @GolloDev 

#### Tareas pendientes
Las tareas pendientes del website se pueden ver en las [PR del iojs-es/website](https://github.com/iojs-es/website/pulls). 

Si no hay tareas pendientes, también puedes ver el documento de [CONTRIBUTING.md](https://github.com/iojs/iojs-es/blob/master/CONTRIBUTING.md) donde encontrarás cómo se van poniendo al día los documentos del website.

**Comment by edsadr** [comment]
@stringparser @vrunoa nos reunimos por chat para que arreglemos el workflow de este WG? tengo una idea para hacer una herramienta que nos facilite el mantenimiento de este repo ... que dicen?

**Comment by stringparser** [comment]
Perfecto, ¿cuando te viene bien?

**Comment by edsadr** [comment]
@stringparser nos encontramos mañana en el chat? me imagino que en la tarde de españa que es la mañana aquí

**Comment by stringparser** [comment]
¿Va bien a las 20:00 UTC? 
http://www.wolframalpha.com/input/?i=20%3A00+UTC

**Comment by sergiolepore** [comment]
Hay lugar en este grupo? :)

**Comment by stringparser** [comment]
Claro tio :smile:

**Comment by stringparser** [comment]
Una cosa, antes de mover el material que corresponde de aquí a [iojs-es/website](https://github.com/iojs-es/website) estaría bien poner aquí los issues pendientes, ¿os parece?

**Comment by vrunoa** [comment]
@edsadr @stringparser a que hora van a hablar ? asi me sumo

**Comment by stringparser** [comment]
No he tenido noticias de @edsadr aún, voy a cortarme el pelo. Dejo el chat abierto.

**Comment by edsadr** [comment]
@vrunoa @stringparser  en 2 horas puedo... y de ahi en adelante..
pueden?

**Comment by stringparser** [comment]
@vrunoa @edsadr pues he ido a pelarme y hasta dentro de una hora no me puedo pasar, en principio si aunque no se si daré luego una vuelta. ¿domingo mejor?

**Comment by vrunoa** [comment]
@stringparser @edsadr justo en 2h a las 4pm(arg) tengo q salir un rato. Mas tarde me parece q a @stringparser se le viene la noche tirando a madrugada. Si quieren hablen, después leo todo cuando vuelva.

**Comment by GolloDev** [comment]
puedo unirme acá?

**Comment by stringparser** [comment]
yep :)

**Comment by stringparser** [comment]
Te he puesto en la lista

**Comment by GolloDev** [comment]
hey, cuales son las tareas? estoy perdido xD

**Comment by stringparser** [comment]
Hey @gollodev, ahora mismo creo que solo hay una pendiente para el website en #90.

**Comment by stringparser** [comment]
Equipo del website hecho en https://github.com/orgs/iojs-es/teams
