### ISSUE TITLE
GT - Revisión

### ISSUE THREAD

**Issue by stringparser** [nodejs/nodejs-es#97]
Muy buenas, 

aquí dejo la lista de la gente que está implicada en el Grupo de Trabajo (GT) de Revisión por ahora como veníamos hablando en #84. Utilicemos este issue para ir viendo cómo nos vamos a organizar en el repositorio correspondiente de la org. [iojs-es](http://github.com/iojs-es) que @edsadr creó donde vamos a ir dividiendo tareas.

Estáis 2 por ahora, dejo un ping para todo el que quiera apuntarse: @iojs/iojs-es.  
@ipeluffo te asigno y añado para estar al tanto de lo que aquí pase porque te he visto más de una vez revisando ;). En cualquier caso, si ves que no asigna a otra persona que tu veas para estar pendiente del issue (includo yo). 

Recordad que @julianduque dejó la propuesta de **estar como máximo en 2 grupos** con la idea de no sobrecargar a la gente con trabajo. En #83 hay una lista de todos los grupos de trabajo y sus miembros.

# Revisión

Equipo encargado de revisar y dar los +1 necesarios a los contenidos antes de publicarlos

#### Miembros
* @italoacasas
* @edsadr 
* @ipeluffo 
* @JoseRoman

**Comment by edsadr** [comment]
Creo que es importante usar un label para revisión así el equipo estará enterado de las tareas pendientes...  @italoacasas @ipeluffo que opinan?

**Comment by italoacasas** [comment]
Completamente de acuerdo contigo
Maybe dos labels?, 
```
Para Revision
```
```
En Revision
```
"Para revision" lo podría el equipo que necesita que revisemos, y nosotros pondríamos "en revision" cuando lo estemos revisando.
Lo digo por el hecho de así nos podemos enfocar en la revision y no estar buscando si hay algo que revisar.

feedback de los dos labels

**Comment by ipeluffo** [comment]
Estoy de acuerdo con el uso de los labels. Sino va a ser muy difícil hacer un seguimiento.
Se que revisión no es lo mejor, pero estaría bueno que se sume más gente porque deberíamos hacer revisión de todo lo que se traduce y podría llevar mucho trabajo.

**Comment by edsadr** [comment]
+1 para esos 2 labels

**Comment by sergiolepore** [comment]
Hay lugar en este grupo? :)

**Comment by ipeluffo** [comment]
Por supuesto @sergiolepore , igualmente falta ver mejor en detalle cómo vamos a hacer las revisiones... porque no se si al grupo trabajará o no con Transifex

**Comment by edsadr** [comment]
@ipeluffo creo que como somos un grupo que trabaja para los demás grupos debemos ser flexibles a la metodología que cada grupo escoja para trabajar... si Documentación trabaja en transifex entonces nosotros hacemos la revisión allá, si trabajan en un repo... entonces allá ... de otra forma terminaríamos diciéndole a los demás grupos como trabajar y no creo que sea buena idea

**Comment by JoseRoman** [comment]
Como puedo ayudar? 1+

**Comment by ipeluffo** [comment]
@edsadr , exactamente por eso que dices hay que esperar la decisión de cómo van a trabajar los distintos grupos ;)

@JoseRoman , ya se darán indicaciones más precisas de cómo ayudar a hacer revisiones pues hay distintos grupos de trabajo y cada uno puede que trabaje de manera distinta.

**Comment by stringparser** [comment]
@JoseRoman, añadido al equipo :)
Y... Equipo de revisión hecho en https://github.com/orgs/iojs-es/teams ;)

**Comment by italoacasas** [comment]
Guys hasta la semana que viene estoy off.
