### ISSUE TITLE
Acomodar (y limpiar) Labels

### ISSUE THREAD

**Issue by ipeluffo** [nodejs/nodejs-es#99]
Buenas @iojs/iojs-es ,

Abro este issue con la idea de acomodar los [labels](https://github.com/iojs/iojs-es/labels) para ordenar mejor los issues.
Acomodar los labels implica:
* Eliminar los que no sirvan
* Renombrar si alguno tiene un nombre poco significativo
* Reasignar los colores
* Agregar alguno que sea necesario

Para ver la lista de labels actuales acceder [aquí](https://github.com/iojs/iojs-es/labels).

Hago la primera propuesta y vamos viendo (sin apuro) qué conviene hacer.
### Eliminar
1. `bug` : no tiene sentido en el contexto de traducción
2. `mejora` : igual que `bug`
3. `traducción API` : deja de tener sentido teniendo el label `documentación`
4. ~~`Reunión` : ver punto 3 en **Agregar**~~

### Agregar
1. `para revisión` : propuesto por @italoacasas en #97 
2. `en revisión` : propuesto por @italoacasas en #97 
3. ~~`administración` : label para identificar los issues relaciones a tareas de administración/mantenimiento, por ejemplo: este issue o un issue para coordinar fecha de reunión~~

### Renombrar
1. ~~Se podría renombrar `Reunión` por `administración`~~
2. ~~Renombrar los labels de los grupos de trabajo (WG) `documentación`, `evangelización`, `revisión`, y `website` como `wg: documentación`, `wg: evangelización`, `wg: revision` y `wg: website`~~

### Colores
1. Los labels más críticos deberían tener un color rojo que llame la atención : \#e11d21
2. Los labels de los grupos otro color único
3. `administración` : otro color
4. Los labels que marquen el estado del issue un único color (excepto los que caigan en el punto 1)

### Dudas
1. `no se hará` : creo que no es necesario este label. Serviría para consultar que issue fueron abiertos y no se hicieron.
2. `duplicado` : lo mismo que para `no se hará`
3. `pregunta` : creo que es muy genérico este label

### Otros
1. Limitar la cantidad de labels asignados por issue: esto lo había propuesto @a0viedo , y creo que es una buena manera de elegir los labels más representativos para un issue. Creo que 3 es un buen límite
2. Uso únicamente de minúsculas para nombres labels (es un detalle)

**Comment by italoacasas** [comment]
@ipeluffo si vamos agregar las dos nuevas labels de revision
```
para revision
```
```
en revision
```

aun hace falta el label de revision?
```
revision
```

**Comment by ipeluffo** [comment]
Creo que los labels `documentación`, `evangelización`, `revisión`, y `website` podrían quedar para marcar los issues correspondientes a cada grupo de trabajo.
Si no son significativos sus nombre, podrían renombrarse como: `WG: documentación` por ejemplo

**Comment by italoacasas** [comment]
+1 por
``` 
wg: documentación
```
``` 
wg: revision
```
``` 
wg: website
```
``` 
wg: evangelizacion
```

**Comment by ipeluffo** [comment]
:+1: , lo agregué a la lista para que alguien más de su +1

**Comment by stringparser** [comment]
+1

**Comment by edsadr** [comment]
+1

**Comment by stringparser** [comment]
Cambiado este último, lo quito de la lista

**Comment by stringparser** [comment]
Añado comentarios

* Eliminar,  +1 para todo
* Agregar, sin comentarios
* Renombrar, +1
* Colores +1 también a todo, 
   - colores únicos: las `wg: ` el que tienen ahora
   - administración: naranja o rojo, pues de la administración dependen bastantes cosas
   - el último punto no lo entiendo
* Dudas, +1 a todo las elilminaría todas excepto `duplicado` que iría en naranja/rojo

En cualquier caso pensad que las labels que hay aquí la mayoría se deberían de eliminar ya que todo se va a dividir en los WGs.

**Comment by julianduque** [comment]
+1 me gusta!

**Comment by ipeluffo** [comment]
@stringparser , es verdad lo que comentas al final, pero esta propuesta de labels podría servir para aplicar en los WGs para usar como referencia.

Respecto al último punto de **Colores**, me refiero a que los labels como `in progress`, `duplicado`, `para revisión`, `en revisión`, `ayuda necesaria` (tal vez) podrían tener el mismo color.

Para hacer más simple, divido los labels que tendrían que tener el mismo color en grupos:

Grupo 1 - Color \#fef2c0
1. `wg: documentación`
2. `wg: evangelización`
3. `wg: revisión`
4. `wg: website`

Grupo 2 - Color ¿?
1. `in progress`
2. `duplicado`
3. `para revisión`
4. `en revisión`

Grupo 3 - Color ¿\#e11d21 = rojo?
1. `ayuda necesaria`
2. `necesita +1`

Grupo 4 - Color ¿\#fbca04 = amarillo?
1. `material`
2. `propuesta`

Grupo 5 - Color \#eb6420 = naranja
1. `administración`

**Comment by ipeluffo** [comment]
Renombré `Reunión` por `administración`, y actualicé el issue original.

**Comment by stringparser** [comment]
@julianduque yeeeah :D

**Comment by stringparser** [comment]
@ipeluffo el Grupo 2 podría unirse con el 5 ya que son todo cosas que si el issue está abierto están en progreso y seguramente pendientes. Y respecto a lo demás, +1 a todo.

**Comment by ipeluffo** [comment]
@stringparser , ¿2 con 5? Pregunto porque en 5 puse `administración` para issues donde se discutan temas más relaciones a la administración del proyecto como coordinación de reuniones o este issue.

**Comment by stringparser** [comment]
@ipeluffo Si, por lo que te he dicho pero lo mismo soy yo :). Si no dejar administración en azul y el Grupo 2 en naranja.

**Comment by stringparser** [comment]
¿le podríamos echar un vistazo a esto y dejarlo listo?
cc @iojs/iojs-es
